name: Pull and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 登录到阿里云容器镜像服务
      - name: Log in to Alibaba Cloud Registry
        run: echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.ALIYUN_REGISTRY_USERNAME }}" registry.cn-guangzhou.aliyuncs.com --password-stdin

      # 拉取和推送 Docker 镜像
      - name: Pull and Push Docker images
        env:
          ALIYUN_NAMESPACE: ${{ secrets.ALIYUN_REGISTRY_NAMESPACE }}
        run: |
          docker pull nginx:latest
          aliyun_image="registry.cn-guangzhou.aliyuncs.com/${{ env.ALIYUN_NAMESPACE }}/nginx:latest"
          docker tag nginx:latest $aliyun_image
          docker push $aliyun_image
